ALTER TABLE call_logs
    ADD COLUMN IF NOT EXISTS cached_tokens INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ttft_ms INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS stream BOOLEAN NOT NULL DEFAULT false;
